### ISSUE TITLE
Clients folder missing from assets

### ISSUE THREAD

**Issue by steven-kraft** [chris062689/game-hook#1]
The clients folder seems to be missing from the game-hook-assets repo. I would like to see an example html file to help me get started. Thank you

**Comment by chris062689** [comment]
I have uploaded an example client of the Pokemon Dashboard used for twitch streams here.
https://github.com/chris062689/game-hook-clients

They don't need to be placed in any specific folder, as it's just a client that connects to the game-hook server.
